In [12]:
import numpy

In [19]:
def genetic_algorithm(inputs, result, new_population):
    print("---------------------------------------")
    print("Genetic algorithm")
    coef_num = len(inputs)
    population_size = 6
    parents_num = 4
    progeny_num = 6
    
    population = new_population
    p = calculate_fitness(population, coef_num)
    while find_solution(p, population) is False:
        parents = select_the_best_individuals(population, p, parents_num)
        progeny = procreation(parents, parents_num, progeny_num)
        progeny_mutation = mutation(progeny)
        population = get_new_population(progeny_mutation, parents)
        p = calculate_fitness(population, coef_num)
    

# Измерение пригодности каждой хромосомы в популяции
# Функция вычисляет сумму произведений между каждым входом и соответствующим ему весом
def calculate_fitness(popul, coef_num):
    p = []
    for i in range(len(popul)):
        s = 0
        for j in range(coef_num):
            s += popul[i][j]*inputs[j]
        r = numpy.abs(result - s) + 1
        p.append(1/r)
    return p

def procreation(parents, parents_num, progeny_num):
    progeny = []
    while True:
        parent1 = np.random.randint(parents_num)
        parent2 = random_without(parents_num, parent1)
        progeny.append(np.append(parents[parent1][:2], parents[parent2][2:]))
        if len(progeny) == progeny_num:
            break
        progeny.append(np.append(parents[parent2][:2], parents[parent1][2:]))
        if len(progeny) == progeny_num:
            break
    return progeny


# Выбор лучших особей текущего поколения в качестве родителей для производства потомков следующего поколения.
def select_the_best_individuals(pop, fitness, num_parents):
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def find_solution(p, population):
    best_result = max(p)
    ind = [i for i in range(len(p)) if p[i] == best_result][0]
    if(best_result >=0.2):
        print('Best solution: {0} with fitness {1}'.format(population[ind], best_result))
        return True
    else:
        return False
    
def get_new_population(progeny, parents):
    new_population = []
    for x in progeny:
        new_population.append(x)
    for i in range(2):
        new_population.append(parents[i])
    return new_population

# Создание нового поколения с использованием кроссовера
def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # Точка, в которой происходит спаривание между двумя родителями
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        # Индекс первого спарившегося родителя
        parent1_idx = k%parents.shape[0]
        # Индекс второго спарившегося родителя
        parent2_idx = (k+1)%parents.shape[0]
        # У нового потомства первая половина генов будет взята от первого родителя, а вторая половина от второго
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    # Мутация изменяет один ген в каждом потомстве случайным образом
    for idx in range(offspring_crossover.shape[0]):
        # Рандомное значение будет добавлено в ген
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover



In [20]:
# y = 3x1 + 1.4x2 + 3.5x3 + 8x4 + 3.6x5 + 9x6
# Инициализация
inputs = [3,1,3,8,3,9]
num_weights = 6
number_of_chromosomes = 8
parents_num = 4
num_generations = 5
result = 23

# У популяции будет number_of_chromosomes хромосом, где каждая хромосома имеет num_weights генов
population_size = (number_of_chromosomes,num_weights)
# Создание начальной популяции
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=population_size)
print("Создание начальной популяции:")
print(new_population)

genetic_algorithm(inputs,result,new_population)

fitness = calculate_fitness(inputs, new_population)
# Вернет индекс решения, соответствующего наилучшей пригодности
best_match_idx = numpy.where(fitness == numpy.max(fitness))
print("---------------------------------------")
print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

Создание начальной популяции:
[[ 2.76588633 -2.88632106 -0.52721897 -1.21226029  0.12277192  0.33736013]
 [-1.45408261 -1.41774323  0.97952047 -0.18890504  2.73941195  0.25076525]
 [ 1.98020125  1.94272708 -0.32807076  1.01674133 -3.0297456   2.01358554]
 [-2.89576724  0.04255036 -2.04347448 -1.66144926 -3.81523056  3.83502349]
 [-0.08870283 -2.0745781   0.79932841  0.50785259 -3.26699934 -1.15751564]
 [-2.93711969 -0.61046693 -3.57819498 -2.11554575  0.88187487  1.31302969]
 [ 1.62548748 -1.88869723 -0.29616194  0.90171037 -0.29362342  2.56295778]
 [ 3.98579539 -3.95002536  1.62656742 -3.2386099   0.96458891  0.82344485]]
---------------------------------------
Genetic algorithm
Best solution: [ 1.98020125  1.94272708 -0.32807076  1.01674133 -3.0297456   2.01358554] with fitness 0.4840078357623483


TypeError: only integer scalar arrays can be converted to a scalar index